version: '3'
services:
  server:
    container_name: server-milko
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/app
    ports:
      - 9993:9993
    depends_on:
      - db
  client:
    container_name: client-milko
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/app
    ports:
      - 80:80
    depends_on:
      - server
  db:
    container_name: postgres-milko
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor123
      POSTGRES_DB: postgres